// Generated by Create API
// https://github.com/kean/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get

extension Paths {
    public static var item: Item {
        Item(path: "/item")
    }

    public struct Item {
        /// Path: `/item`
        public let path: String
    }
}

extension Paths.Item {
    public func itemID(_ itemID: Int) -> WithJSON {
        WithJSON(path: "\(path)/\(itemID).json")
    }

    public struct WithJSON {
        /// Path: `/item/{itemId}.json`
        public let path: String

        /// Get item by ID
        ///
        /// Returns an item
        public var get: Request<HNKit.Item> {
            .get(path)
        }
    }
}

extension Paths {
    public static var user: User {
        User(path: "/user")
    }

    public struct User {
        /// Path: `/user`
        public let path: String
    }
}

extension Paths.User {
    public func username(_ username: String) -> WithJSON {
        WithJSON(path: "\(path)/\(username).json")
    }

    public struct WithJSON {
        /// Path: `/user/{username}.json`
        public let path: String

        /// Get user by username
        ///
        /// Returns a user
        public var get: Request<HNKit.User> {
            .get(path)
        }
    }
}

public enum Paths {}
